/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Big_building(props) {
  const { nodes, materials } = useGLTF("/models/Big_Building.glb");
  return (
    <group {...props} dispose={null}>
   
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3_Big_1.geometry}
          material={materials.BrickRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3_Big_2.geometry}
          material={materials.Beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3_Big_3.geometry}
          material={materials.LightYellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3_Big_4.geometry}
          material={materials.Brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3_Big_5.geometry}
          material={materials.DarkGrey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3_Big_6.geometry}
          material={materials.Grey}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Big_Building.glb");
