/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tablet(props) {
  const { nodes, materials } = useGLTF("/models/Tablet.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox003.geometry}
        material={materials["04___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl001.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox001_1.geometry}
        material={materials["02___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox001_1_1.geometry}
        material={materials["01___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox001_1_2.geometry}
        material={materials["04___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox002_1.geometry}
        material={materials["01___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox002_1_1.geometry}
        material={materials["04___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox004_1.geometry}
        material={materials["01___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox004_1_1.geometry}
        material={materials["04___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox005_1.geometry}
        material={materials["01___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox005_1_1.geometry}
        material={materials["04___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox006_1.geometry}
        material={materials["03___Default"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox006_1_1.geometry}
        material={materials["04___Default"]}
      />
    </group>
  );
}

useGLTF.preload("/models/Tablet.glb");

