/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Animated Woman.glb -o src/components/AnimatedWoman.jsx -r public
*/

// 绑定动画
import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAtom } from "jotai";
import React, { useEffect, useMemo, useRef, useState } from "react";
import { SkeletonUtils } from "three-stdlib";
import { useGrid } from "../hooks/useGrid";
import { useSelector } from "react-redux";
import { userAtom } from "./SocketManager";
import { motion } from "framer-motion-3d";
// import { userRoleAtom } from "./UI";
// import { userNameAtom } from "./UI";

import { useContext } from 'react';
import UserRoleContext from './UserRoleContext';

const MOVEMENT_SPEED = 4;
//const [userRole, setUserRole] = useState('student'); 
const userRole ="student"

export function Avatar({
  id,
  character,
  ...props
}) {
  const { role, name } = character || { role: 'student', name: '访客' };
  
  return (
    <Html position-y={2.2}>
      <div className="w-20 text-white text-center p-3 px-6 -translate-x-1/2">
        <p className="absolute text-small">
          {role === 'teacher' ? '教师' : '学生'}: {name}
        </p>
      </div>
    </Html>
  );
}

useGLTF.preload(
  localStorage.getItem("avatarURL") ||
   // "https://models.readyplayer.me/64f0265b1db75f90dcfd9e2c.glb?meshlod=1&quality=medium"  // 设置画质中等
   "https://models.readyplayer.me/6575b1a3b21c8b3e80ba1a83.glb?meshlod=1&quality=medium"
);

useGLTF.preload("/animations/M_Walk_001.glb");
useGLTF.preload("/animations/M_Standing_Idle_001.glb");
useGLTF.preload("/animations/M_Dances_011.glb");
useGLTF.preload("/animations/M_Standing_Expressions_001.glb");
