/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Animated Woman.glb -o src/components/AnimatedWoman.jsx -r public
*/

// 绑定动画
import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAtom } from "jotai";
import React, { useEffect, useMemo, useRef, useState } from "react";
import { SkeletonUtils } from "three-stdlib";
import { useGrid } from "../hooks/useGrid";
import { useSelector } from "react-redux";
import { userAtom } from "./SocketManager";
import { motion } from "framer-motion-3d";
// import { userRoleAtom } from "./UI";
// import { userNameAtom } from "./UI";

import { useContext } from 'react';
import UserRoleContext from './UserRoleContext';
import { avatarUrlAtom } from '../store/atoms';

const MOVEMENT_SPEED = 4;
//const [userRole, setUserRole] = useState('student'); 
const userRole ="student"

export function Avatar({
  id,
  role,
  name,
  ...props
}) {
  const [avatarUrl] = useAtom(avatarUrlAtom);
  const { scene } = useGLTF(avatarUrl);
  const { userRole, userName } = useContext(UserRoleContext);

  return (
    <group {...props}>
      <Html position={[0, 2, 0]}>
        <div style={{
          background: 'rgba(0,0,0,0.5)',
          color: 'white',
          padding: '5px 10px',
          borderRadius: '5px',
          textAlign: 'center'
        }}>
          <div>{name || userName}</div>
          <div>{role || userRole}</div>
        </div>
      </Html>
      <primitive object={scene.clone()} />
    </group>
  );
}
